### ISSUE TITLE
missing default order

### ISSUE THREAD

**Issue by ghost** [vicb/bsmSelect#15]
you can reorder items by bsmselect but there is probably no way how to force item order when building list without changing select options orders 

example 
- add few items
- reorder
- submit 
- save with order

but there is missing way how to tell bsmselect that you want items with custom/saved order

**Comment by intropedro** [comment]
The way to do that is as follows. 

The original select:

```
<select id="myselect" name="test" multiple="multiple">
    <option value="40">A</option>
    <option value="75">B</option>
    <option value="41">C</option>
    <option selected="selected" data-bsm-order="1" value="29">D</option>
    <option value="39">E</option>
    <option value="23">F</option>
    <option selected="selected" data-bsm-order="0" value="44">G</option>
    <option value="62">H</option>
    <option value="38">I</option>
    <option value="61">J</option>
</select>
```

And the Javascript:

```
jQuery("#myselect").bsmSelect({
    addItemTarget: 'original',
    plugins: [jQuery.bsmSelect.plugins.sortable(), jQuery.bsmSelect.plugins.compatibility()]
});
```

**Comment by SUPERNOVI** [comment]
@vicb I really don't understand why you are struggling to understand this. Let me try.

I have a list of customer titles, alphabetical:
```
Dr
Mr
Mrs
Sir
```

I want to allow some or all of these to be assigned and the order to be customised.
For example the user may want **Mr** and **Mrs** first because they are more common.

However for finding the option you desire I wish to keep the alphabetical order.

Another way of looking at it is the original select is the SOURCE and the BSMSelect is the ASSIGNED.

So with that in mind I have the exact same quirk where if I reload the page fresh, the `data-bsm-order` attribute is not honoured on my hidden select list. The bsm renders perfectly but it ignores my field that I want to save...UNLESS, I move one item. If I move an item the whole order of the original select is fixed!

So how can I tell bsm to do this during the call of `$(".customer-titles").bsmSelect({...})` ??

I guess there are two ways of approaching it, either allow option to sort bsmSelect so we can build the select server side in correct order OR the way I think works better, honour the `data-bsm-order` on the hidden select in the bsm init.
